apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1 #Changed the replicas from 1 to 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: rssauri/hellojs:v1
        ports:
        - containerPort: 80
